version: '3'
services:
  redis:
    image: redis:latest
    container_name: redisserver
    restart: unless-stopped
  mainApp:
    image: franko172000/diagnosis-ass:latest
    container_name: diagnosis-app
    restart: unless-stopped
    depends_on:
      - redis
