version: '3'
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_DB: diagnosis_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redisserver
    restart: unless-stopped
  mainApp:
    image: franko172000/diagnosis-ass:latest
    container_name: diagnosis-app
    ports:
      - 4000:3300
    environment:
      DB_HOST: postgresdb
      DB_SCHEMA: diagnosis_db
      DB_USER: postgres
      DB_PASS: postgres_user
      DB_PORT: 5432
      REDIS_SERVER: redisserver
    restart: unless-stopped
    depends_on:
      - postgresdb
